<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>0.0.1</Version>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.8" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
		<PackageReference Include="NLog.Extensions.Logging" Version="6.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MockSocket.Tcp\MockSocket.Tcp.csproj" />
		<ProjectReference Include="..\MockSocket.Udp\MockSocket.Udp.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.Development.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
